### ISSUE TITLE
return -1 becomes return- 1

### ISSUE THREAD

**Issue by klaufir** [eudoxia0/cmacro#10]
Given the following input file

``` c
// file: test.cmc
int main() {
    return -1;
}
```

Cmc generates the following output

``` bash
$ cmc test.cmc -o test.c && cat test.c

int main () {
return- 1;
}
```

And this code doesn't compile, while the original is valid C code.

edit: Wow, reponse under 4 minutes: thats top notch support :) Thanks for looking into it!

**Comment by eudoxia0** [comment]
Thanks. I think this will just be a matter of improving the parsing of negative numbers.
